### PR TITLE
Do not wait for checkpoint from previous build

### PR DESCRIPTION
**Pull request by mbektchiev**
Fixes an issue with result archiver getting stuck for a long time in concurrent builds.
A similar issue has been fixed in the JUnit Jenkins plugin:

https://issues.jenkins-ci.org/browse/JENKINS-10234
https://github.com/jenkinsci/jenkins/commit/90ff9f806fcac1a58f4bd40bfcc4ed5273ff116a

### CODE REVIEW

**Comment by kinow** [comment]
Thanks for the PR @mbektchiev ! Will try to take a look at this issue tonight. Released CCM plug-in last night, maybe we can release NUnit this week too with this fix :smile:

**Comment by mbektchiev** [comment]
Hi @kinow, have you managed to take a look at this fix? We've been using it for almost a month now and haven't found any problems with it so far.

**Comment by kinow** [comment]
Hi @mbektchiev, not yet, just finished the mozilla science global sprint. Opening my Eclipse workspace to see if I can try it right now.

**Comment by kinow** [comment]
Looking good!! Thanks @mbektchiev ! Releasing a new version right now.

**Comment by kinow** [comment]
0.17 released. I'm going to try to update the Wiki docs (Wiki has been behaving oddly these past days), and it should be available through the update centre in the next hours. Thanks and sorry for the delay.

**Pull request merged**
