### PR TITLE
Fix JENKINS-5674

### PR DESCRIPTION
**Pull request by timotei**
When using .SetName() on a TestCaseData
the end result in the NUnit results file
won't be using the format of a method call

Issue: JENKINS-5674

### CODE REVIEW

**Comment by timotei** [comment]
@slide Is it possible to have a release?

**Comment by slide** [comment]
I am planning on a release this week. There are a few other items I want to look at possibly including.

**Comment by timotei** [comment]
@slide any news? :D

**Comment by timotei** [comment]
@slide Any chance we can get a release? We really need this fix :)

**Comment by timotei** [comment]
Oh. Don't know how I missed it. Thank you!

**Pull request merged**
